### ISSUE TITLE
Bruh just use youtubeloop.com

### ISSUE THREAD

**Issue by webguy24** [RCMSUnblockers/schooltube#2]
This is useless just use youtubeloop they don’t check traffic data just only what site you’re on

**Comment by iamsirsammy** [comment]
Hello!
I would prefer if you would tell us what happened in an issue instead of telling us your conclusions.
I don't know exactly what happened, but I can guess one of three things,
1. yewtu.be (what schooltube uses) was slow the day of you commenting and you did not give it time to load.
2. My sense of time is broken and this was when yewtu.be wasn't working do to changes with youtube. (Which lasted about a day.)
3. This was the day I accidentally broke the code.
Whatever happened, yewtu.be was never blocked by MCPS using iBoss, however it was blocked with the blue wifi system, which still allows embeds, schooltube still works, (now cooltube.glitch.me), and youtubeloop.com is currently not working at all. I could draw a conclusion that you lied about youtubeloop.com ever working at all for nefarious purposes, but am instead taking the more logical route of youtubeloop being changed.

I hope we can work with you in the future.

**Comment by webguy24** [comment]
Sorry, I meant youtubeloop.net. Not .com. Just a typo.
